# Port
server:
  port: 80

# Database
spring:
  datasource:
    # ✨ MySQL URL에 allowPublicKeyRetrieval=true&useSSL=false 추가
    url: jdbc:mysql://localhost:3306/naver_market?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieal=true
    username: root
    password: happy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update  # 권장되는 ddl-auto 옵션 (none, update, create, create-drop 중 선택)
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Naming strategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          storage_engine: innodb
          show_sql: true
          format_sql: true
          user_sql_comments: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html

# JWT Configuration
jwt:
  # JWT Secret Key (Base64 encoded, 최소 32바이트 이상 권장)
  # 이 값을 반드시 강력하고 유일한 값으로 변경해주세요!
  # 예시: openssl rand -base64 32 명령어로 생성 가능
  # 현재는 "secret"이라는 문자열을 Base64로 인코딩한 값
  secret: c2VjcmV0
  # JWT Expiration Time (in milliseconds)
  # 1시간 = 3600000 (60 * 60 * 1000)
  # 24시간 = 86400000 (24 * 60 * 60 * 1000)
  expiration: 86400000

logging:
  level:
    org:
      springframework: 
        transaction: TRACE
      orm:
        jpa:
          JpaTransactionManager: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        resource:
          transaction:
            backend:
              jdbc:
                internal:
                  JdbcResourceLocalTransactionCoordinatorImpl: TRACE
