# Port
server:
  port: 80

# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/naver_market?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieal=true
    username: root
    password: happy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update  # 권장되는 ddl-auto 옵션 (none, update, create, create-drop 중 선택)
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Naming strategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          storage_engine: innodb
          show_sql: true
          format_sql: true
          user_sql_comments: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html

# JWT Configuration
jwt:
  # JWT Secret Key
  # navermarketprojectjwttokensecretkey
  secret: bmF2ZXJtYXJrZXRwcm9qZWN0and0dG9rZW5zZWNyZXRrZXk=
  # JWT Expiration Time (in milliseconds)
  # 1시간 = 3600000 (60 * 60 * 1000)
  # 24시간 = 86400000 (24 * 60 * 60 * 1000)
  expiration: 86400000

file:
  upload-dir: uploads

logging:
  level:
    org:
      springframework: 
        transaction: TRACE
      orm:
        jpa:
          JpaTransactionManager: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        resource:
          transaction:
            backend:
              jdbc:
                internal:
                  JdbcResourceLocalTransactionCoordinatorImpl: TRACE
